version: '3.9'
services:
  clinic-project-dev:
    container_name: 'clinic-project-dev'
    command: 'npm run start:dev'
    depends_on:
      - cl-mysql-dev
    build: '.'
    ports:
      - '${PORT}:${PORT}'
    volumes:
      - ./.:/var/www/clinic-project
    environment:
      - LANG=C.UTF-8
      - LC_ALL=C.UTF-8
      - NODE_ENV="development"
      - DB_HOST=${DB_HOST}
      - DB_USERNAME=${DB_USERNAME}
      - DB_PASSWORD=${DB_PASSWORD}
      - DB_DATABASE=${DB_DATABASE}
      - DB_PORT=${DB_PORT}

  cl-mysql-dev:
    image: mysql
    container_name: cl-mysql-dev
    environment:
      - MYSQL_USER=${DB_USERNAME}
      - MYSQL_PASSWORD=${DB_PASSWORD}
      - MYSQL_ROOT_PASSWORD=${DB_PASSWORD}
      - MYSQL_DATABASE=${DB_DATABASE}
